# flathub_url: https://dl.flathub.org/repo/flathub.flatpakrepo
user: joydeep
kubectl_version: v1.23.1
pkgs:
- appimagelauncher
- gnome-tweaks
- python3-pip
- nodejs
- npm
- qbittorrent
# # - python3
# - openssl
# # - terraform 
# - nodejs
# # - opi
# - qbittorrent
# - vlc
# - zsh
# # - cherrytree
# - flameshot
# # - github-cli
# # - toolbox
# - deepin-terminal
# - aws-cli
# - code
# - fzf
# - kubectl
# - helm
