- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# - name: Print the package facts
#   ansible.builtin.debug:
#     var: ansible_facts.packages

- name: APT Signing key for terraform
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes
  become_method: "sudo"
  when: not "'terraform' in ansible_facts.packages"

- name: Add terraform sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com impish main
    state: present
  when: not "'terraform' in ansible_facts.packages"

- name: Install terraform
  package: name=terraform state=present
  when: not "'terraform' in ansible_facts.packages"
