- name: check kubectx location
  stat:
    path: /opt/kubectx
  register: kubectx

- name: Clone kubectx
  git:
    repo: https://github.com/ahmetb/kubectx
    dest: /opt/kubectx
  become: yes
  become_method: sudo
  when: not kubectx.stat.exists


- name: Create symbolic link kubectx
  file:
    src: /opt/kubectx/kubectx
    dest: /usr/local/bin/kubectx
    state: link
  become: yes
  become_method: sudo
  when: not kubectx.stat.exists

- name: Create symbolic link kubens
  file:
    src: /opt/kubectx/kubens
    dest: /usr/local/bin/kubens
    state: link
  become: yes
  become_method: sudo  
  when: not kubectx.stat.exists
