---
# tasks file for opensuse-setup

- name: install packages
  package: name={{ pkgs }} state=present update_cache=yes

- name: Add flathub repo
  flatpak_remote: name=flathub state=present flatpakrepo_url={{ flathub_url }} when={{ install_flatpaks }}

- name: Install multiple packages
  community.general.flatpak: name={{ flatpaks }} state=present when={{ install_flatpaks }}

- name: adding existing user '{{ user }}' to group sudo
  user:
    name: '{{ user }}'
    groups: lxd
    append: yes
  become: yes