---
- name: check zinit location
  stat:
    path: $HOME/.local/share/zinit/zinit.git
  register: zinit


# tasks file for zinit
- name: Download zinit installer
  get_url: 
    url: https://git.io/zinit-install 
    dest: ~/zinit-install.sh
    mode: 0777
  when: not zinit.stat.exists
  

- name: Execute the zinit-install.sh
  shell: ~/zinit-install.sh
  when: not zinit.stat.exists

- name: Remove the zinit-install.sh
  file: path=~/zinit-install.sh
  when: not zinit.stat.exists

- name: zinit scripts into .zshrc
  shell: |
    echo "zinit load zdharma-continuum/history-search-multi-word" >> ~/.zshrc
    echo "zinit light zsh-users/zsh-autosuggestions" >> ~/.zshrc
    echo "zinit light zdharma-continuum/fast-syntax-highlighting" >> ~/.zshrc
    echo "zinit snippet https://gist.githubusercontent.com/hightemp/5071909/raw/" >> ~/.zshr
  when: not zinit.stat.exists
  